---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: ssh-hardening-instance
    image: geerlingguy/docker-ubuntu2204-ansible
    privileged: true

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml

verifier:
  name: ansible