---
- name: Create ops user
  user:
    name: "{{ ops_user }}"
    groups: sudo
    append: true
    shell: /bin/bash
    create_home: true
    
- name: Create .ssh directory
  file:
    path: "/home/{{ ops_user }}/.ssh"
    state: directory
    owner: "{{ ops_user }}"
    group: "{{ ops_user }}"
    mode: "0700"